FROM node:alpine

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

ENV PATH="./node_modules/.bin:$PATH"

COPY ./src ./src
COPY ./public ./public

EXPOSE 3000

CMD ["yarn", "start-client"]